/**
 * Database Setup Helper
 * 
 * Provides interactive guidance for setting up database configuration
 * Can be run standalone to help users configure their database connection
 */

import * as readline from 'readline';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setupDatabaseConfig(): Promise<void> {
  console.log('\n🔧 Database Configuration Setup Helper\n');
  console.log('This tool will help you configure your database connection.\n');

  const envPath = join(process.cwd(), '.env');
  
  // Read existing .env if it exists
  let envContent = '';
  if (existsSync(envPath)) {
    envContent = readFileSync(envPath, 'utf-8');
    console.log('✅ Found existing .env file\n');
  } else {
    console.log('⚠️  No .env file found. Will create a new one.\n');
  }

  // Ask which authentication method to use
  console.log('Which authentication method do you want to use?');
  console.log('1. SQL Server Authentication (sa account) - Recommended');
  console.log('2. Windows Authentication (your Windows user)\n');
  
  const authChoice = await question('Enter your choice (1 or 2): ');
  
  if (authChoice === '1') {
    // SQL Server Authentication
    console.log('\n📝 SQL Server Authentication Setup\n');
    
    const server = await question('SQL Server address (e.g., localhost,1433 or localhost\\SQLEXPRESS): ') || 'localhost,1433';
    const database = await question('Database name [rmhsample]: ') || 'rmhsample';
    const user = await question('SQL Server username [sa]: ') || 'sa';
    const password = await question('SQL Server password: ');
    
    if (!password || password.trim() === '') {
      console.error('\n❌ Error: Password is required for SQL Server Authentication');
      console.log('\n💡 If you don\'t know your password:');
      console.log('   1. Open SQL Server Management Studio (SSMS)');
      console.log('   2. Connect using Windows Authentication');
      console.log('   3. Go to: Security → Logins → sa → Properties');
      console.log('   4. You can view/reset the password there\n');
      rl.close();
      process.exit(1);
    }

    // Build .env content
    envContent = `# SQL Server Database Configuration
# Generated by setup helper

# SQL Server instance
DB_SERVER=${server}

# Database name
DB_DATABASE=${database}

# Authentication method
DB_USE_WINDOWS_AUTH=false

# SQL Server authentication
DB_USER=${user}
DB_PASSWORD=${password}

# Connection options
DB_ENCRYPT=false
DB_TRUST_CERTIFICATE=true
`;

    console.log('\n✅ Configuration saved to .env file');
    console.log('\n⚠️  Important next steps:');
    console.log('   1. Ensure SQL Server is in "Mixed Mode" authentication');
    console.log('      - SSMS → Server Properties → Security');
    console.log('      - Select "SQL Server and Windows Authentication mode"');
    console.log('      - Restart SQL Server service');
    console.log('   2. Verify sa account is enabled:');
    console.log('      - SSMS → Security → Logins → sa → Properties → Status');
    console.log('      - Ensure "Login" is set to "Enabled"\n');

  } else if (authChoice === '2') {
    // Windows Authentication
    console.log('\n📝 Windows Authentication Setup\n');
    
    const server = await question('SQL Server address (e.g., localhost,1433 or localhost\\SQLEXPRESS): ') || 'localhost,1433';
    const database = await question('Database name [rmhsample]: ') || 'rmhsample';

    // Build .env content
    envContent = `# SQL Server Database Configuration
# Generated by setup helper

# SQL Server instance
DB_SERVER=${server}

# Database name
DB_DATABASE=${database}

# Authentication method
DB_USE_WINDOWS_AUTH=true

# Connection options
DB_ENCRYPT=false
DB_TRUST_CERTIFICATE=true
`;

    console.log('\n✅ Configuration saved to .env file');
    console.log('\n⚠️  Important: Ensure your Windows user has SQL Server permissions:');
    console.log('   1. Open SQL Server Management Studio (SSMS)');
    console.log('   2. Connect using Windows Authentication');
    console.log('   3. Go to: Security → Logins → Right-click → New Login');
    console.log('   4. Select "Windows Authentication"');
    console.log('   5. Search for your Windows username');
    console.log('   6. Under "Server Roles", check "sysadmin" (or appropriate role)');
    console.log('   7. Under "User Mappings", select your database and assign roles\n');

  } else {
    console.error('\n❌ Invalid choice. Please run the setup again and select 1 or 2.');
    rl.close();
    process.exit(1);
  }

  // Write .env file
  writeFileSync(envPath, envContent, 'utf-8');
  console.log('✅ Configuration complete!');
  console.log('\n🚀 Next steps:');
  console.log('   1. Review the .env file');
  console.log('   2. Restart your application');
  console.log('   3. Test the connection\n');

  rl.close();
}

export { setupDatabaseConfig };

// Execute if run directly
setupDatabaseConfig().catch(error => {
  console.error('Error during setup:', error);
  rl.close();
  process.exit(1);
});

